// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAevKfXcsrZDTjoaIH_yQccaRCCo_paoK4',
    appId: '1:150789753257:web:f12da60b46973500f49cb8',
    messagingSenderId: '150789753257',
    projectId: 'praktikum-b7222',
    authDomain: 'praktikum-b7222.firebaseapp.com',
    databaseURL: 'https://praktikum-b7222-default-rtdb.firebaseio.com',
    storageBucket: 'praktikum-b7222.appspot.com',
    measurementId: 'G-XK6SJBD2ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDZB2O7YLpm00NpG4owUbFFhcPEDNR3I',
    appId: '1:150789753257:android:6fd3f923f688592cf49cb8',
    messagingSenderId: '150789753257',
    projectId: 'praktikum-b7222',
    databaseURL: 'https://praktikum-b7222-default-rtdb.firebaseio.com',
    storageBucket: 'praktikum-b7222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN39G7BU6K4KbpCdSt5ImnPkCfQNodR3I',
    appId: '1:150789753257:ios:f942a661c7864852f49cb8',
    messagingSenderId: '150789753257',
    projectId: 'praktikum-b7222',
    databaseURL: 'https://praktikum-b7222-default-rtdb.firebaseio.com',
    storageBucket: 'praktikum-b7222.appspot.com',
    iosClientId: '150789753257-esd9pbt3b27g14u350i2n6h6advh14do.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsaMobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN39G7BU6K4KbpCdSt5ImnPkCfQNodR3I',
    appId: '1:150789753257:ios:f942a661c7864852f49cb8',
    messagingSenderId: '150789753257',
    projectId: 'praktikum-b7222',
    databaseURL: 'https://praktikum-b7222-default-rtdb.firebaseio.com',
    storageBucket: 'praktikum-b7222.appspot.com',
    iosClientId: '150789753257-esd9pbt3b27g14u350i2n6h6advh14do.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsaMobileFlutter',
  );
}
